server:
  port: 8020
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
spring:
  application:
    name: hera-admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
logging:
  level:
    com.demin.hera.Feign: debug
