server:
  port: 8001
spring:
  application:
    name: hera-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
zuul:
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    admin-service:
      path: /admin/**
      service-id: hera-admin
      strip-prefix: true
    essearch-service:
      path: /search/**
      service-id: hera-essearch
      strip-prefix: true
    shop-service:
      path: /shop/**
      service-id: hera-shop
      strip-prefix: true    # 转发路径不包含/shop/前缀

  ignored-services: "*"     #禁用默认路由
ribbon:
  eureka:
    enabled: true
