server:
  port: 8040
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
spring:
  application:
    name: hera-essearch
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    elasticsearch:
      cluster-name: demin
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
