server:
  port: 8030
spring:
  application:
    name: hera-shop
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
logging:
  level:
    com.demin.hera.Feign: debug
    com.demin.hera.Controller: debug