# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
http://localhost:8020/category/getAll?pageNum=10&pageSize=10

###

http://localhost:8020/category/findById?categoryId=cde220934dfa4f0f9e8e939190bf48e2

###############

POST http://localhost:8020/category/save
Accept : application/json
Content-Type: application/json

{
        "name": "手机",
        "imageAddr": "testURl",
        "isParent": 1,
        "parentId": null,
        "createTime": "2019-06-05T13:14:24",
        "updateTime": "2019-06-05T13:14:24"
}

###

###